name: Integration Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nightly 2020-08-20
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-08-20
        override: true
        profile: minimal
        default: true
    - name: Build
      run: cargo build --release
    - name: Test bounds_check
      run: |
        cargo run --release --bin prover tests/resources/bounds_check
        cargo run --release --bin verifier tests/resources/bounds_check
    - name: Test equality
      run: |
        cargo run --release --bin prover tests/resources/equality
        cargo run --release --bin verifier tests/resources/equality
    - name: Test inequality
      run: |
        cargo run --release --bin prover tests/resources/inequality
        cargo run --release --bin verifier tests/resources/inequality
    - name: Test less_than
      run: |
        cargo run --release --bin prover tests/resources/less_than
        cargo run --release --bin verifier tests/resources/less_than
    - name: Test merkle_tree
      run: |
        cargo run --release --bin prover tests/resources/merkle_tree
        cargo run --release --bin verifier tests/resources/merkle_tree
    - name: Test mimc_hash
      run: |
        cargo run --release --bin prover tests/resources/mimc_hash
        cargo run --release --bin verifier tests/resources/mimc_hash
    - name: Test set_membership
      run: |
        cargo run --release --bin prover tests/resources/set_membership
        cargo run --release --bin verifier tests/resources/set_membership
    - name: Test merkle_root
        run: |
          cargo run --release --bin prover tests/resources/merkle_root
          cargo run --release --bin verifier tests/resources/merkle_root
    - name: Test or_conjunction
      run: |
        cargo run --release --bin prover tests/resources/or
        cargo run --release --bin verifier tests/resources/or
        cargo run --release --bin prover tests/resources/or2
        cargo run --release --bin verifier tests/resources/or2
        cargo run --release --bin prover tests/resources/or3
        cargo run --release --bin verifier tests/resources/or3
        cargo run --release --bin prover tests/resources/or4
        cargo run --release --bin verifier tests/resources/or4
        cargo run --release --bin prover tests/resources/or5
        cargo run --release --bin verifier tests/resources/or5
